import type {
  AdminUser,
  AdminProduct,
  AdminCategory,
  AdminBrand,
  AdminOrder,
  AdminCustomer,
  AdminReview,
  AdminCoupon,
  AdminInventoryItem,
  DashboardStats,
  SalesTrend,
  TopProduct,
  StoreSettings,
  TaxSettings,
  ShippingSettings,
  PaymentSettings,
  EmailSettings,
  NotificationSettings,
  AdminAddress,
} from "./admin-types";

// ==============================
// ADMIN USERS
// ==============================
export const mockAdminUsers: AdminUser[] = [
  {
    id: 1,
    email: "admin@amart.com",
    name: "Admin User",
    role: "admin",
    avatar: null,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    last_login: "2025-06-08T10:30:00Z",
  },
  {
    id: 2,
    email: "manager@amart.com",
    name: "Manager User",
    role: "manager",
    avatar: null,
    is_active: true,
    created_at: "2024-02-15T00:00:00Z",
    last_login: "2025-06-07T08:15:00Z",
  },
  {
    id: 3,
    email: "staff@amart.com",
    name: "Staff User",
    role: "staff",
    avatar: null,
    is_active: true,
    created_at: "2024-03-01T00:00:00Z",
    last_login: "2025-06-06T14:00:00Z",
  },
];

// ==============================
// CATEGORIES
// ==============================
export const mockCategories: AdminCategory[] = [
  {
    id: 1,
    name: "Fruits & Vegetables",
    slug: "fruits-and-vegetables",
    description: "Fresh fruits and vegetables sourced directly from farms",
    image: "/images/categories/vegetables.jpg",
    parent: null,
    product_count: 45,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Dairy & Eggs",
    slug: "dairy-and-eggs",
    description: "Fresh dairy products and farm eggs",
    image: "/images/categories/dairy.jpg",
    parent: null,
    product_count: 30,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 3,
    name: "Meat & Poultry",
    slug: "meat-and-poultry",
    description: "Premium cuts of meat and poultry",
    image: "/images/categories/meat.jpg",
    parent: null,
    product_count: 25,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 4,
    name: "Seafood",
    slug: "seafood",
    description: "Fresh and frozen seafood",
    image: "/images/categories/seafood.jpg",
    parent: null,
    product_count: 20,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 5,
    name: "Bakery & Bread",
    slug: "bakery-and-bread",
    description: "Freshly baked bread and pastries",
    image: "/images/categories/bakery.jpg",
    parent: null,
    product_count: 35,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 6,
    name: "Beverages",
    slug: "beverages",
    description: "Soft drinks, juices, and more",
    image: "/images/categories/beverages.jpg",
    parent: null,
    product_count: 40,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 7,
    name: "Snacks & Chips",
    slug: "snacks-and-chips",
    description: "Chips, cookies, and snack foods",
    image: "/images/categories/snacks.jpg",
    parent: null,
    product_count: 50,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 8,
    name: "Frozen Foods",
    slug: "frozen-foods",
    description: "Frozen meals, vegetables, and ice cream",
    image: "/images/categories/frozen.jpg",
    parent: null,
    product_count: 28,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 9,
    name: "Organic Fruits",
    slug: "organic-fruits",
    description: "Certified organic fruits",
    image: "/images/categories/organic-fruits.jpg",
    parent: 1,
    product_count: 15,
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2025-04-01T00:00:00Z",
  },
  {
    id: 10,
    name: "Organic Vegetables",
    slug: "organic-vegetables",
    description: "Certified organic vegetables",
    image: "/images/categories/organic-vegetables.jpg",
    parent: 1,
    product_count: 18,
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2025-04-01T00:00:00Z",
  },
];

// ==============================
// BRANDS
// ==============================
export const mockBrands: AdminBrand[] = [
  {
    id: 1,
    name: "Fresh Farm",
    slug: "fresh-farm",
    description: "Farm-fresh produce and dairy",
    logo: null,
    website: "https://freshfarm.example.com",
    product_count: 30,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Nature's Best",
    slug: "natures-best",
    description: "Organic and natural products",
    logo: null,
    website: null,
    product_count: 25,
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 3,
    name: "Daily Essentials",
    slug: "daily-essentials",
    description: "Everyday household essentials",
    logo: null,
    website: null,
    product_count: 40,
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 4,
    name: "Premium Select",
    slug: "premium-select",
    description: "Premium quality gourmet products",
    logo: null,
    website: "https://premiumselect.example.com",
    product_count: 20,
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 5,
    name: "Green Valley",
    slug: "green-valley",
    description: "Sustainable and eco-friendly products",
    logo: null,
    website: null,
    product_count: 35,
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
];

// ==============================
// PRODUCTS
// ==============================
export const mockProducts: AdminProduct[] = [
  {
    id: 1,
    name: "Fresh Organic Bananas",
    slug: "fresh-organic-bananas",
    sku: "FRT-001",
    description: "Handpicked organic bananas sourced from sustainable farms. Rich in potassium and naturally sweet.",
    short_description: "Sweet and nutritious organic bananas",
    price: 120,
    discount_price: 99,
    stock: 500,
    category: 1,
    brand: 1,
    tags: ["organic", "fruit", "banana"],
    images: ["/images/products/banana.jpg"],
    status: "active",
    is_featured: true,
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2025-05-15T00:00:00Z",
  },
  {
    id: 2,
    name: "Fresh Whole Milk - 1L",
    slug: "fresh-whole-milk-1l",
    sku: "DRY-001",
    description: "Farm-fresh whole milk, pasteurized and homogenized. Rich in calcium and vitamin D.",
    short_description: "Farm-fresh whole milk 1 liter",
    price: 130,
    discount_price: null,
    stock: 300,
    category: 2,
    brand: 1,
    tags: ["dairy", "milk", "fresh"],
    images: ["/images/products/milk.jpg"],
    status: "active",
    is_featured: true,
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2025-05-15T00:00:00Z",
  },
  {
    id: 3,
    name: "Free Range Eggs - 12pc",
    slug: "free-range-eggs-12pc",
    sku: "DRY-002",
    description: "Premium free-range eggs from cage-free hens. High in protein and omega-3 fatty acids.",
    short_description: "Farm fresh free-range eggs dozen",
    price: 150,
    discount_price: 135,
    stock: 200,
    category: 2,
    brand: 2,
    tags: ["eggs", "protein", "free-range"],
    images: ["/images/products/eggs.jpg"],
    status: "active",
    is_featured: true,
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2025-05-15T00:00:00Z",
  },
  {
    id: 4,
    name: "Sourdough Bread",
    slug: "sourdough-bread",
    sku: "BAK-001",
    description: "Artisan sourdough bread made with natural fermentation. Crusty exterior with soft interior.",
    short_description: "Artisan sourdough bread",
    price: 250,
    discount_price: null,
    stock: 50,
    category: 5,
    brand: 4,
    tags: ["bread", "sourdough", "bakery"],
    images: ["/images/products/sourdough.jpg"],
    status: "active",
    is_featured: false,
    created_at: "2024-06-15T00:00:00Z",
    updated_at: "2025-05-10T00:00:00Z",
  },
  {
    id: 5,
    name: "Organic Chicken Breast - 500g",
    slug: "organic-chicken-breast-500g",
    sku: "MET-001",
    description: "Boneless skinless organic chicken breast. Hormone-free and antibiotic-free.",
    short_description: "Organic boneless chicken breast",
    price: 450,
    discount_price: 420,
    stock: 100,
    category: 3,
    brand: 2,
    tags: ["chicken", "organic", "meat"],
    images: ["/images/products/chicken.jpg"],
    status: "active",
    is_featured: true,
    created_at: "2024-06-20T00:00:00Z",
    updated_at: "2025-05-12T00:00:00Z",
  },
  {
    id: 6,
    name: "Atlantic Salmon Fillet - 250g",
    slug: "atlantic-salmon-fillet-250g",
    sku: "SEA-001",
    description: "Fresh Atlantic salmon fillet, rich in omega-3. Sustainably sourced.",
    short_description: "Fresh Atlantic salmon fillet",
    price: 650,
    discount_price: null,
    stock: 40,
    category: 4,
    brand: 4,
    tags: ["salmon", "seafood", "fish"],
    images: ["/images/products/salmon.jpg"],
    status: "active",
    is_featured: false,
    created_at: "2024-07-01T00:00:00Z",
    updated_at: "2025-05-08T00:00:00Z",
  },
  {
    id: 7,
    name: "Organic Brown Rice - 2kg",
    slug: "organic-brown-rice-2kg",
    sku: "GRN-001",
    description: "Premium organic brown rice, rich in fiber and nutrients.",
    short_description: "Premium organic brown rice",
    price: 320,
    discount_price: 290,
    stock: 150,
    category: 8,
    brand: 2,
    tags: ["rice", "organic", "grains"],
    images: ["/images/products/rice.jpg"],
    status: "active",
    is_featured: false,
    created_at: "2024-07-05T00:00:00Z",
    updated_at: "2025-05-05T00:00:00Z",
  },
  {
    id: 8,
    name: "Mixed Fruit Juice - 1L",
    slug: "mixed-fruit-juice-1l",
    sku: "BEV-001",
    description: "Refreshing mixed fruit juice with no added sugar. Made from real fruits.",
    short_description: "No sugar added mixed fruit juice",
    price: 180,
    discount_price: 150,
    stock: 200,
    category: 6,
    brand: 3,
    tags: ["juice", "beverage", "fruit"],
    images: ["/images/products/juice.jpg"],
    status: "active",
    is_featured: false,
    created_at: "2024-07-10T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 9,
    name: "Potato Chips - Classic Salted",
    slug: "potato-chips-classic-salted",
    sku: "SNK-001",
    description: "Crispy potato chips with the perfect amount of salt.",
    short_description: "Classic salted potato chips",
    price: 60,
    discount_price: null,
    stock: 500,
    category: 7,
    brand: 3,
    tags: ["chips", "snacks", "salted"],
    images: ["/images/products/chips.jpg"],
    status: "active",
    is_featured: false,
    created_at: "2024-07-15T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
  },
  {
    id: 10,
    name: "Vanilla Ice Cream - 500ml",
    slug: "vanilla-ice-cream-500ml",
    sku: "FRZ-001",
    description: "Creamy vanilla ice cream made with real vanilla beans.",
    short_description: "Premium vanilla ice cream",
    price: 350,
    discount_price: 299,
    stock: 80,
    category: 8,
    brand: 4,
    tags: ["ice-cream", "frozen", "dessert"],
    images: ["/images/products/ice-cream.jpg"],
    status: "active",
    is_featured: false,
    created_at: "2024-08-01T00:00:00Z",
    updated_at: "2025-04-28T00:00:00Z",
  },
  {
    id: 11,
    name: "Organic Tomatoes - 1kg",
    slug: "organic-tomatoes-1kg",
    sku: "FRT-002",
    description: "Vine-ripened organic tomatoes, perfect for salads and cooking.",
    short_description: "Fresh organic tomatoes",
    price: 80,
    discount_price: null,
    stock: 10,
    category: 1,
    brand: 1,
    tags: ["tomato", "organic", "vegetable"],
    images: ["/images/products/tomatoes.jpg"],
    status: "active",
    is_featured: false,
    created_at: "2024-08-05T00:00:00Z",
    updated_at: "2025-04-25T00:00:00Z",
  },
  {
    id: 12,
    name: "Greek Yogurt - 400g",
    slug: "greek-yogurt-400g",
    sku: "DRY-003",
    description: "Thick and creamy Greek yogurt, high in protein.",
    short_description: "Creamy Greek yogurt",
    price: 220,
    discount_price: 199,
    stock: 0,
    category: 2,
    brand: 1,
    tags: ["yogurt", "dairy", "protein"],
    images: ["/images/products/yogurt.jpg"],
    status: "active",
    is_featured: false,
    created_at: "2024-08-10T00:00:00Z",
    updated_at: "2025-04-20T00:00:00Z",
  },
];

// ==============================
// CUSTOMERS
// ==============================
export const mockCustomers: AdminCustomer[] = [
  {
    id: 1,
    email: "rahman.karim@email.com",
    name: "Rahman Karim",
    phone: "+8801712345678",
    avatar: null,
    total_orders: 12,
    total_spent: 24500,
    is_active: true,
    is_blocked: false,
    joined_at: "2024-06-01T00:00:00Z",
    last_order_at: "2025-06-05T00:00:00Z",
    addresses: [
      {
        id: 1,
        label: "Home",
        full_name: "Rahman Karim",
        phone: "+8801712345678",
        street: "42 Gulshan Avenue, Road 12",
        city: "Dhaka",
        area: "Gulshan",
        postal_code: "1212",
        is_default: true,
      },
    ],
  },
  {
    id: 2,
    email: "fatima.begum@email.com",
    name: "Fatima Begum",
    phone: "+8801712345679",
    avatar: null,
    total_orders: 8,
    total_spent: 18300,
    is_active: true,
    is_blocked: false,
    joined_at: "2024-07-15T00:00:00Z",
    last_order_at: "2025-06-03T00:00:00Z",
    addresses: [
      {
        id: 2,
        label: "Home",
        full_name: "Fatima Begum",
        phone: "+8801712345679",
        street: "15 Banani Road 11",
        city: "Dhaka",
        area: "Banani",
        postal_code: "1213",
        is_default: true,
      },
    ],
  },
  {
    id: 3,
    email: "arif.hossain@email.com",
    name: "Arif Hossain",
    phone: "+8801712345680",
    avatar: null,
    total_orders: 5,
    total_spent: 9200,
    is_active: true,
    is_blocked: false,
    joined_at: "2024-09-01T00:00:00Z",
    last_order_at: "2025-05-28T00:00:00Z",
    addresses: [
      {
        id: 3,
        label: "Office",
        full_name: "Arif Hossain",
        phone: "+8801712345680",
        street: "10 Motijheel Commercial Area",
        city: "Dhaka",
        area: "Motijheel",
        postal_code: "1223",
        is_default: true,
      },
    ],
  },
  {
    id: 4,
    email: "nusrat.jahan@email.com",
    name: "Nusrat Jahan",
    phone: "+8801712345681",
    avatar: null,
    total_orders: 15,
    total_spent: 32100,
    is_active: true,
    is_blocked: false,
    joined_at: "2024-05-01T00:00:00Z",
    last_order_at: "2025-06-06T00:00:00Z",
    addresses: [
      {
        id: 4,
        label: "Home",
        full_name: "Nusrat Jahan",
        phone: "+8801712345681",
        street: "25 Dhanmondi Road 6",
        city: "Dhaka",
        area: "Dhanmondi",
        postal_code: "1205",
        is_default: true,
      },
    ],
  },
  {
    id: 5,
    email: "kabir.ahmed@email.com",
    name: "Kabir Ahmed",
    phone: "+8801712345682",
    avatar: null,
    total_orders: 3,
    total_spent: 5400,
    is_active: false,
    is_blocked: true,
    joined_at: "2024-10-01T00:00:00Z",
    last_order_at: "2025-04-15T00:00:00Z",
    addresses: [],
  },
  {
    id: 6,
    email: "tahmina.islam@email.com",
    name: "Tahmina Islam",
    phone: "+8801712345683",
    avatar: null,
    total_orders: 20,
    total_spent: 45000,
    is_active: true,
    is_blocked: false,
    joined_at: "2024-04-01T00:00:00Z",
    last_order_at: "2025-06-07T00:00:00Z",
    addresses: [
      {
        id: 5,
        label: "Home",
        full_name: "Tahmina Islam",
        phone: "+8801712345683",
        street: "8 Uttara Sector 10",
        city: "Dhaka",
        area: "Uttara",
        postal_code: "1230",
        is_default: true,
      },
    ],
  },
  {
    id: 7,
    email: "shahin.mia@email.com",
    name: "Shahin Mia",
    phone: "+8801712345684",
    avatar: null,
    total_orders: 7,
    total_spent: 11200,
    is_active: true,
    is_blocked: false,
    joined_at: "2024-11-01T00:00:00Z",
    last_order_at: "2025-05-20T00:00:00Z",
    addresses: [
      {
        id: 6,
        label: "Home",
        full_name: "Shahin Mia",
        phone: "+8801712345684",
        street: "30 Mirpur Road",
        city: "Dhaka",
        area: "Mirpur",
        postal_code: "1216",
        is_default: true,
      },
    ],
  },
];

// ==============================
// ORDERS
// ==============================
export const mockOrders: AdminOrder[] = [
  {
    id: 1,
    order_id: "AMART-2025-0001",
    user: 1,
    customer_name: "Rahman Karim",
    customer_email: "rahman.karim@email.com",
    items: [
      {
        id: 1,
        product_name: "Fresh Organic Bananas",
        product_id: 1,
        quantity: 2,
        price: 99,
        image: "/images/products/banana.jpg",
        total: 198,
      },
      {
        id: 2,
        product_name: "Fresh Whole Milk - 1L",
        product_id: 2,
        quantity: 1,
        price: 130,
        image: "/images/products/milk.jpg",
        total: 130,
      },
    ],
    total_amount: 328,
    delivery_charge: 40,
    discount: 0,
    status: "delivered",
    payment_status: "paid",
    payment_method: "bkash",
    shipping_address: {
      id: 1,
      label: "Home",
      full_name: "Rahman Karim",
      phone: "+8801712345678",
      street: "42 Gulshan Avenue, Road 12",
      city: "Dhaka",
      area: "Gulshan",
      postal_code: "1212",
      is_default: true,
    },
    order_notes: "",
    created_at: "2025-06-05T10:30:00Z",
    updated_at: "2025-06-07T14:20:00Z",
  },
  {
    id: 2,
    order_id: "AMART-2025-0002",
    user: 2,
    customer_name: "Fatima Begum",
    customer_email: "fatima.begum@email.com",
    items: [
      {
        id: 3,
        product_name: "Free Range Eggs - 12pc",
        product_id: 3,
        quantity: 2,
        price: 135,
        image: "/images/products/eggs.jpg",
        total: 270,
      },
      {
        id: 4,
        product_name: "Sourdough Bread",
        product_id: 4,
        quantity: 1,
        price: 250,
        image: "/images/products/sourdough.jpg",
        total: 250,
      },
      {
        id: 5,
        product_name: "Organic Chicken Breast - 500g",
        product_id: 5,
        quantity: 1,
        price: 420,
        image: "/images/products/chicken.jpg",
        total: 420,
      },
    ],
    total_amount: 940,
    delivery_charge: 40,
    discount: 50,
    status: "processing",
    payment_status: "paid",
    payment_method: "cod",
    shipping_address: {
      id: 2,
      label: "Home",
      full_name: "Fatima Begum",
      phone: "+8801712345679",
      street: "15 Banani Road 11",
      city: "Dhaka",
      area: "Banani",
      postal_code: "1213",
      is_default: true,
    },
    order_notes: "Please deliver before 6 PM",
    created_at: "2025-06-03T09:15:00Z",
    updated_at: "2025-06-04T11:00:00Z",
  },
  {
    id: 3,
    order_id: "AMART-2025-0003",
    user: 4,
    customer_name: "Nusrat Jahan",
    customer_email: "nusrat.jahan@email.com",
    items: [
      {
        id: 6,
        product_name: "Atlantic Salmon Fillet - 250g",
        product_id: 6,
        quantity: 2,
        price: 650,
        image: "/images/products/salmon.jpg",
        total: 1300,
      },
      {
        id: 7,
        product_name: "Organic Brown Rice - 2kg",
        product_id: 7,
        quantity: 1,
        price: 290,
        image: "/images/products/rice.jpg",
        total: 290,
      },
    ],
    total_amount: 1590,
    delivery_charge: 0,
    discount: 0,
    status: "pending",
    payment_status: "pending",
    payment_method: "bkash",
    shipping_address: {
      id: 4,
      label: "Home",
      full_name: "Nusrat Jahan",
      phone: "+8801712345681",
      street: "25 Dhanmondi Road 6",
      city: "Dhaka",
      area: "Dhanmondi",
      postal_code: "1205",
      is_default: true,
    },
    order_notes: "",
    created_at: "2025-06-06T15:45:00Z",
    updated_at: "2025-06-06T15:45:00Z",
  },
  {
    id: 4,
    order_id: "AMART-2025-0004",
    user: 6,
    customer_name: "Tahmina Islam",
    customer_email: "tahmina.islam@email.com",
    items: [
      {
        id: 8,
        product_name: "Mixed Fruit Juice - 1L",
        product_id: 8,
        quantity: 3,
        price: 150,
        image: "/images/products/juice.jpg",
        total: 450,
      },
      {
        id: 9,
        product_name: "Potato Chips - Classic Salted",
        product_id: 9,
        quantity: 5,
        price: 60,
        image: "/images/products/chips.jpg",
        total: 300,
      },
      {
        id: 10,
        product_name: "Vanilla Ice Cream - 500ml",
        product_id: 10,
        quantity: 2,
        price: 299,
        image: "/images/products/ice-cream.jpg",
        total: 598,
      },
    ],
    total_amount: 1348,
    delivery_charge: 40,
    discount: 100,
    status: "shipped",
    payment_status: "paid",
    payment_method: "nagad",
    shipping_address: {
      id: 5,
      label: "Home",
      full_name: "Tahmina Islam",
      phone: "+8801712345683",
      street: "8 Uttara Sector 10",
      city: "Dhaka",
      area: "Uttara",
      postal_code: "1230",
      is_default: true,
    },
    order_notes: "Leave at the gate",
    created_at: "2025-06-07T08:00:00Z",
    updated_at: "2025-06-07T16:30:00Z",
  },
  {
    id: 5,
    order_id: "AMART-2025-0005",
    user: 3,
    customer_name: "Arif Hossain",
    customer_email: "arif.hossain@email.com",
    items: [
      {
        id: 11,
        product_name: "Organic Tomatoes - 1kg",
        product_id: 11,
        quantity: 1,
        price: 80,
        image: "/images/products/tomatoes.jpg",
        total: 80,
      },
    ],
    total_amount: 80,
    delivery_charge: 40,
    discount: 0,
    status: "cancelled",
    payment_status: "refunded",
    payment_method: "cod",
    shipping_address: {
      id: 3,
      label: "Office",
      full_name: "Arif Hossain",
      phone: "+8801712345680",
      street: "10 Motijheel Commercial Area",
      city: "Dhaka",
      area: "Motijheel",
      postal_code: "1223",
      is_default: true,
    },
    order_notes: "Cancelled by customer",
    created_at: "2025-05-28T12:00:00Z",
    updated_at: "2025-05-29T09:00:00Z",
  },
  {
    id: 6,
    order_id: "AMART-2025-0006",
    user: 7,
    customer_name: "Shahin Mia",
    customer_email: "shahin.mia@email.com",
    items: [
      {
        id: 1,
        product_name: "Fresh Organic Bananas",
        product_id: 1,
        quantity: 1,
        price: 99,
        image: "/images/products/banana.jpg",
        total: 99,
      },
      {
        id: 3,
        product_name: "Free Range Eggs - 12pc",
        product_id: 3,
        quantity: 1,
        price: 135,
        image: "/images/products/eggs.jpg",
        total: 135,
      },
      {
        id: 4,
        product_name: "Sourdough Bread",
        product_id: 4,
        quantity: 2,
        price: 250,
        image: "/images/products/sourdough.jpg",
        total: 500,
      },
      {
        id: 7,
        product_name: "Organic Brown Rice - 2kg",
        product_id: 7,
        quantity: 1,
        price: 290,
        image: "/images/products/rice.jpg",
        total: 290,
      },
    ],
    total_amount: 1024,
    delivery_charge: 0,
    discount: 0,
    status: "pending",
    payment_status: "pending",
    payment_method: "bkash",
    shipping_address: {
      id: 6,
      label: "Home",
      full_name: "Shahin Mia",
      phone: "+8801712345684",
      street: "30 Mirpur Road",
      city: "Dhaka",
      area: "Mirpur",
      postal_code: "1216",
      is_default: true,
    },
    order_notes: "",
    created_at: "2025-06-07T18:20:00Z",
    updated_at: "2025-06-07T18:20:00Z",
  },
];

// ==============================
// REVIEWS
// ==============================
export const mockReviews: AdminReview[] = [
  {
    id: 1,
    product: 1,
    product_name: "Fresh Organic Bananas",
    product_image: "/images/products/banana.jpg",
    customer: 1,
    customer_name: "Rahman Karim",
    customer_avatar: null,
    rating: 5,
    review: "Excellent quality bananas! Very fresh and sweet. Will order again.",
    status: "approved",
    created_at: "2025-06-06T10:00:00Z",
  },
  {
    id: 2,
    product: 2,
    product_name: "Fresh Whole Milk - 1L",
    product_image: "/images/products/milk.jpg",
    customer: 2,
    customer_name: "Fatima Begum",
    customer_avatar: null,
    rating: 4,
    review: "Good quality milk. Fresh and creamy. Delivery was on time.",
    status: "approved",
    created_at: "2025-06-05T14:30:00Z",
  },
  {
    id: 3,
    product: 3,
    product_name: "Free Range Eggs - 12pc",
    product_image: "/images/products/eggs.jpg",
    customer: 4,
    customer_name: "Nusrat Jahan",
    customer_avatar: null,
    rating: 5,
    review: "Best eggs in town! The yolks are so orange and fresh.",
    status: "approved",
    created_at: "2025-06-04T09:15:00Z",
  },
  {
    id: 4,
    product: 5,
    product_name: "Organic Chicken Breast - 500g",
    product_image: "/images/products/chicken.jpg",
    customer: 6,
    customer_name: "Tahmina Islam",
    customer_avatar: null,
    rating: 3,
    review: "Chicken was okay. A bit smaller portion than expected for the price.",
    status: "pending",
    created_at: "2025-06-07T11:00:00Z",
  },
  {
    id: 5,
    product: 10,
    product_name: "Vanilla Ice Cream - 500ml",
    product_image: "/images/products/ice-cream.jpg",
    customer: 7,
    customer_name: "Shahin Mia",
    customer_avatar: null,
    rating: 1,
    review: "Ice cream was melted by the time it arrived. Very disappointed.",
    status: "pending",
    created_at: "2025-06-07T19:00:00Z",
  },
  {
    id: 6,
    product: 4,
    product_name: "Sourdough Bread",
    product_image: "/images/products/sourdough.jpg",
    customer: 3,
    customer_name: "Arif Hossain",
    customer_avatar: null,
    rating: 4,
    review: "Great sourdough! Crusty exterior and soft inside. Freshly baked.",
    status: "rejected",
    created_at: "2025-05-29T08:00:00Z",
  },
  {
    id: 7,
    product: 8,
    product_name: "Mixed Fruit Juice - 1L",
    product_image: "/images/products/juice.jpg",
    customer: 1,
    customer_name: "Rahman Karim",
    customer_avatar: null,
    rating: 5,
    review: "Delicious juice! No added sugar is a big plus. Love it!",
    status: "approved",
    created_at: "2025-06-03T16:45:00Z",
  },
];

// ==============================
// COUPONS
// ==============================
export const mockCoupons: AdminCoupon[] = [
  {
    id: 1,
    code: "WELCOME10",
    discount_type: "percentage",
    discount_value: 10,
    min_order_amount: 500,
    max_uses: 1000,
    used_count: 245,
    is_active: true,
    start_date: "2025-01-01T00:00:00Z",
    expiry_date: "2025-12-31T23:59:59Z",
    created_at: "2024-12-15T00:00:00Z",
  },
  {
    id: 2,
    code: "SAVE50",
    discount_type: "fixed",
    discount_value: 50,
    min_order_amount: 300,
    max_uses: 500,
    used_count: 120,
    is_active: true,
    start_date: "2025-03-01T00:00:00Z",
    expiry_date: "2025-06-30T23:59:59Z",
    created_at: "2025-02-20T00:00:00Z",
  },
  {
    id: 3,
    code: "FREESHIP",
    discount_type: "fixed",
    discount_value: 40,
    min_order_amount: 800,
    max_uses: 300,
    used_count: 300,
    is_active: false,
    start_date: "2025-04-01T00:00:00Z",
    expiry_date: "2025-05-31T23:59:59Z",
    created_at: "2025-03-25T00:00:00Z",
  },
  {
    id: 4,
    code: "SUMMER20",
    discount_type: "percentage",
    discount_value: 20,
    min_order_amount: 1000,
    max_uses: 200,
    used_count: 45,
    is_active: true,
    start_date: "2025-06-01T00:00:00Z",
    expiry_date: "2025-08-31T23:59:59Z",
    created_at: "2025-05-25T00:00:00Z",
  },
  {
    id: 5,
    code: "FIRST100",
    discount_type: "fixed",
    discount_value: 100,
    min_order_amount: 0,
    max_uses: 100,
    used_count: 0,
    is_active: true,
    start_date: "2025-06-01T00:00:00Z",
    expiry_date: "2025-07-01T23:59:59Z",
    created_at: "2025-05-30T00:00:00Z",
  },
];

// ==============================
// INVENTORY
// ==============================
export const mockInventory: AdminInventoryItem[] = [
  {
    id: 1,
    product: 1,
    product_name: "Fresh Organic Bananas",
    product_image: "/images/products/banana.jpg",
    sku: "FRT-001",
    stock: 500,
    reserved_stock: 25,
    available_stock: 475,
    low_stock_threshold: 50,
    is_low_stock: false,
    updated_at: "2025-06-08T08:00:00Z",
  },
  {
    id: 2,
    product: 2,
    product_name: "Fresh Whole Milk - 1L",
    product_image: "/images/products/milk.jpg",
    sku: "DRY-001",
    stock: 300,
    reserved_stock: 15,
    available_stock: 285,
    low_stock_threshold: 30,
    is_low_stock: false,
    updated_at: "2025-06-08T08:00:00Z",
  },
  {
    id: 3,
    product: 3,
    product_name: "Free Range Eggs - 12pc",
    product_image: "/images/products/eggs.jpg",
    sku: "DRY-002",
    stock: 200,
    reserved_stock: 10,
    available_stock: 190,
    low_stock_threshold: 25,
    is_low_stock: false,
    updated_at: "2025-06-08T08:00:00Z",
  },
  {
    id: 4,
    product: 4,
    product_name: "Sourdough Bread",
    product_image: "/images/products/sourdough.jpg",
    sku: "BAK-001",
    stock: 50,
    reserved_stock: 5,
    available_stock: 45,
    low_stock_threshold: 15,
    is_low_stock: false,
    updated_at: "2025-06-08T08:00:00Z",
  },
  {
    id: 5,
    product: 5,
    product_name: "Organic Chicken Breast - 500g",
    product_image: "/images/products/chicken.jpg",
    sku: "MET-001",
    stock: 100,
    reserved_stock: 8,
    available_stock: 92,
    low_stock_threshold: 20,
    is_low_stock: false,
    updated_at: "2025-06-08T08:00:00Z",
  },
  {
    id: 6,
    product: 6,
    product_name: "Atlantic Salmon Fillet - 250g",
    product_image: "/images/products/salmon.jpg",
    sku: "SEA-001",
    stock: 40,
    reserved_stock: 3,
    available_stock: 37,
    low_stock_threshold: 10,
    is_low_stock: false,
    updated_at: "2025-06-08T08:00:00Z",
  },
  {
    id: 7,
    product: 11,
    product_name: "Organic Tomatoes - 1kg",
    product_image: "/images/products/tomatoes.jpg",
    sku: "FRT-002",
    stock: 10,
    reserved_stock: 2,
    available_stock: 8,
    low_stock_threshold: 20,
    is_low_stock: true,
    updated_at: "2025-06-08T08:00:00Z",
  },
  {
    id: 8,
    product: 12,
    product_name: "Greek Yogurt - 400g",
    product_image: "/images/products/yogurt.jpg",
    sku: "DRY-003",
    stock: 0,
    reserved_stock: 0,
    available_stock: 0,
    low_stock_threshold: 15,
    is_low_stock: true,
    updated_at: "2025-06-08T08:00:00Z",
  },
];

// ==============================
// DASHBOARD STATS
// ==============================
export const mockDashboardStats: DashboardStats = {
  total_revenue: 1567800,
  total_orders: 1256,
  total_customers: 892,
  total_products: 248,
  pending_orders: 23,
  cancelled_orders: 15,
  low_stock_products: 8,
  revenue_growth: 12.5,
  orders_growth: 8.3,
  customers_growth: 15.7,
};

// ==============================
// SALES TREND
// ==============================
export const mockSalesTrend: SalesTrend[] = [
  { month: "Jan", revenue: 98000, orders: 78, growth: 5.2 },
  { month: "Feb", revenue: 112000, orders: 85, growth: 14.3 },
  { month: "Mar", revenue: 135000, orders: 102, growth: 20.5 },
  { month: "Apr", revenue: 128000, orders: 96, growth: -5.2 },
  { month: "May", revenue: 156000, orders: 118, growth: 21.9 },
  { month: "Jun", revenue: 142000, orders: 105, growth: -9.0 },
  { month: "Jul", revenue: 165000, orders: 125, growth: 16.2 },
  { month: "Aug", revenue: 148000, orders: 112, growth: -10.3 },
  { month: "Sep", revenue: 172000, orders: 130, growth: 16.2 },
  { month: "Oct", revenue: 158000, orders: 120, growth: -8.1 },
  { month: "Nov", revenue: 190000, orders: 145, growth: 20.3 },
  { month: "Dec", revenue: 220000, orders: 168, growth: 15.8 },
];

// ==============================
// TOP PRODUCTS
// ==============================
export const mockTopProducts: TopProduct[] = [
  { id: 1, name: "Fresh Organic Bananas", image: "/images/products/banana.jpg", total_sold: 1250, revenue: 123750 },
  { id: 2, name: "Fresh Whole Milk - 1L", image: "/images/products/milk.jpg", total_sold: 980, revenue: 127400 },
  { id: 3, name: "Free Range Eggs - 12pc", image: "/images/products/eggs.jpg", total_sold: 850, revenue: 114750 },
  { id: 4, name: "Organic Chicken Breast - 500g", image: "/images/products/chicken.jpg", total_sold: 620, revenue: 279000 },
  { id: 5, name: "Mixed Fruit Juice - 1L", image: "/images/products/juice.jpg", total_sold: 580, revenue: 87000 },
];

// ==============================
// REVENUE DATA (monthly)
// ==============================
export const mockRevenueData = [
  { date: "2025-01", revenue: 980000, orders: 78 },
  { date: "2025-02", revenue: 1120000, orders: 85 },
  { date: "2025-03", revenue: 1350000, orders: 102 },
  { date: "2025-04", revenue: 1280000, orders: 96 },
  { date: "2025-05", revenue: 1560000, orders: 118 },
  { date: "2025-06", revenue: 720000, orders: 55 },
];

// ==============================
// SETTINGS
// ==============================
export const mockStoreSettings: StoreSettings = {
  store_name: "Amart",
  store_email: "hello@amart.com",
  store_phone: "+8801712345678",
  store_address: "123 Gulshan Avenue, Dhaka 1212",
  currency: "BDT",
  timezone: "Asia/Dhaka",
  logo: "/amart.png",
  favicon: null,
};

export const mockTaxSettings: TaxSettings = {
  tax_enabled: true,
  tax_rate: 5,
  tax_inclusive: true,
  tax_label: "VAT",
};

export const mockShippingSettings: ShippingSettings = {
  free_shipping_min_amount: 1000,
  standard_shipping_fee: 40,
  express_shipping_fee: 100,
  shipping_zones: ["Dhaka City", "Dhaka Suburbs", "Chattogram", "Other Cities"],
};

export const mockPaymentSettings: PaymentSettings = {
  stripe_enabled: false,
  stripe_publishable_key: "",
  cod_enabled: true,
  bkash_enabled: true,
  nagad_enabled: true,
};

export const mockEmailSettings: EmailSettings = {
  smtp_host: "smtp.sendgrid.net",
  smtp_port: 587,
  smtp_user: "apikey",
  smtp_password: "",
  from_email: "noreply@amart.com",
  from_name: "Amart",
};

export const mockNotificationSettings: NotificationSettings = {
  order_confirmation: true,
  order_shipped: true,
  order_delivered: true,
  low_stock_alert: true,
  new_customer_welcome: true,
  admin_new_order: true,
};

// ==============================
// PERMISSIONS MAP
// ==============================
export type Permission =
  | "view_dashboard"
  | "manage_products"
  | "manage_categories"
  | "manage_brands"
  | "manage_orders"
  | "manage_customers"
  | "manage_reviews"
  | "manage_coupons"
  | "manage_inventory"
  | "view_analytics"
  | "view_reports"
  | "manage_settings"
  | "manage_staff";

export const rolePermissions: Record<string, Permission[]> = {
  admin: [
    "view_dashboard",
    "manage_products",
    "manage_categories",
    "manage_brands",
    "manage_orders",
    "manage_customers",
    "manage_reviews",
    "manage_coupons",
    "manage_inventory",
    "view_analytics",
    "view_reports",
    "manage_settings",
    "manage_staff",
  ],
  manager: [
    "view_dashboard",
    "manage_products",
    "manage_categories",
    "manage_brands",
    "manage_orders",
    "manage_customers",
    "manage_reviews",
    "manage_coupons",
    "manage_inventory",
    "view_analytics",
    "view_reports",
  ],
  staff: [
    "view_dashboard",
    "manage_products",
    "manage_categories",
    "manage_brands",
    "manage_orders",
    "view_analytics",
  ],
};
